basePath: /
consumes:
- application/json
definitions:
  models.Recipe:
    properties:
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      published_at:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    name: Roshan Lamichhane
  description: This is a basic recipes API in go (Gin).
  title: Recipes API
  version: 1.0.0
paths:
  /recipes:
    post:
      consumes:
      - application/json
      description: Create a new recipe
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Recipe'
        "400":
          description: Bad Request
      summary: Create a new recipe
produces:
- pplication/json
swagger: "2.0"
